/**
 * Download the portfolio's typefaces once, then serve them from our own origin.
 *
 * The page must make no outbound requests, and Google Fonts is an outbound
 * request. Latin subset only — the player UI has no other need.
 *
 * Run after a font change:  bun run fonts
 */
import { mkdir } from "node:fs/promises";
import { join } from "node:path";

const OUT_DIR = "vendor/fonts";
const CSS_OUT = "styles/fonts.css";

/** Google Fonts serves woff2 only to browsers that advertise support. */
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

const API =
  "https://fonts.googleapis.com/css2?family=Calistoga&family=Inter:wght@400;500;600&display=swap";

const { fetch } = Bun;

await mkdir(OUT_DIR, { recursive: true });

const css = await (await fetch(API, { headers: { "user-agent": UA } })).text();

/**
 * Each face is preceded by a `/* subset *\/` comment, so walk the file in
 * comment+block pairs and keep latin only.
 */
const faces: string[] = [];
const blocks = css.split("/*").slice(1);

for (const block of blocks) {
  const subset = block.slice(0, block.indexOf("*/")).trim();
  if (subset !== "latin") continue;

  faces.push(block.slice(block.indexOf("*/") + 2));
}

const rules: string[] = [];
let bytes = 0;

/** Identical bytes across weights means Google served one variable font — keep one copy. */
const byHash = new Map<string, { family: string; weights: number[]; data: Uint8Array }>();

for (const face of faces) {
  const family = face.match(/font-family:\s*'([^']+)'/)?.[1];
  const weight = face.match(/font-weight:\s*(\d+)/)?.[1];
  const remote = face.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];

  if (!family || !weight || !remote) continue;

  const data = new Uint8Array(await (await fetch(remote, { headers: { "user-agent": UA } })).arrayBuffer());
  const hash = [...data.slice(0, 512)].reduce((acc, byte) => (acc * 31 + byte) >>> 0, 7).toString(16);
  const entry = byHash.get(hash);

  if (entry) {
    entry.weights.push(Number(weight));
  } else {
    byHash.set(hash, { family, weights: [Number(weight)], data });
  }
}

for (const { family, weights, data } of byHash.values()) {
  const name = `${family.toLowerCase().replace(/\s+/g, "-")}.woff2`;
  await Bun.write(join(OUT_DIR, name), data);
  bytes += data.byteLength;

  const [low, high] = [Math.min(...weights), Math.max(...weights)];
  const descriptor = low === high ? String(low) : `${low} ${high}`;

  rules.push(
    [
      "@font-face {",
      `  font-family: "${family}";`,
      "  font-style: normal;",
      `  font-weight: ${descriptor};`,
      "  font-display: swap;",
      `  src: url("../vendor/fonts/${name}") format("woff2");`,
      "}",
    ].join("\n"),
  );
}

await Bun.write(
  CSS_OUT,
  [
    "/* Generated by `bun run fonts` — do not edit by hand. SIL Open Font License 1.1. */",
    "",
    ...rules,
    "",
  ].join("\n"),
);

console.log(`fonts: ${rules.length} faces, ${(bytes / 1024).toFixed(0)} KB -> ${OUT_DIR}, ${CSS_OUT}`);
